from selenium import webdriver
import time 

driver=webdriver.Chrome()
driver.get('https://login.microsoftonline.com/common/oauth2/authorize?client_id=871c010f-5e61-4fb1-83ac-98610a7e9110&response_type=code%20id_token&scope=openid%20profile%20offline_access&state=OpenIdConnect.AuthenticationProperties%3DFDg_t671TLg8-bdGwNUfIeZcGbxMZxr7wT2GmdBzN6yZ8YZhM7kwuL-wmHpeSqGNyGt-uoglZUXhFADjFdGAKr-u0YSLeC9WZbEEksGPPvrVGSrVgwEulXCxTvm9qaih-5wFWu9j3lxiiB0Ej-S8oA&response_mode=form_post&nonce=637746026255201756.NjZiNjRlMTMtZTQ2Mi00OTkwLTkyZWEtMmU3YzViZDcwYTE4MWI4Zjc5ZmUtYTYyOC00NGU2LWFjZTktYzhlMWQ0MDg4N2Zh&site_id=500453&redirect_uri=https%3A%2F%2Fapp.powerbi.com%2F%3FnoSignUpCheck%3D1&post_logout_redirect_uri=https%3A%2F%2Fapp.powerbi.com%2F%3FnoSignUpCheck%3D1&resource=https%3A%2F%2Fanalysis.windows.net%2Fpowerbi%2Fapi&nux=1&msafed=0&x-client-SKU=ID_NET461&x-client-ver=5.6.0.0')
email = 'carlos.veche@raizen.com'
time.sleep(4)
email = driver.find_element_by_xpath('//*[@id="i0116"]')
email.click()
email.send_keys('carlos.veche@raizen.com')
botão = driver.find_element_by_xpath('//*[@id="idSIButton9"]')
botão.click()
time.sleep(5)
senha = driver.find_element_by_xpath('//*[@id="passwordInput"]')
senha.click()
time.sleep(5)
senha.send_keys("1804Josi*.")
botão_acesso = driver.find_element_by_xpath('//*[@id="submitButton"]')
botão_acesso.click()
time.sleep(23)
botão_operador_pro=driver.find_element_by_xpath('//*[@id="content"]/home/div/favorites-widget/div/pbi-card[1]/pbi-card-content')
botão_operador_pro.click()
time.sleep(10)   
transbordo = driver.find_element_by_xpath("//span[@title='Transbordo']")
transbordo.click()   
time.sleep(5)
transbordo_1 = driver.find_element_by_xpath('//*[@id="pvExplorationHost"]/div/div/exploration/div/explore-canvas/div/div[2]/div/div[2]/div[2]/visual-container-repeat/visual-container[8]/transform/div/div[3]/div/visual-modern/div/div/div[2]/div/div')
transbordo_1.click()
time.sleep(5)
inicio = driver.find_element_by_xpath('//*[@id="pvExplorationHost"]/div/div/exploration/div/explore-canvas/div/div[2]/div/div[2]/div[2]/visual-container-repeat/visual-container[2]/transform/div/div[3]/div/visual-modern/div/div')
inicio.click()
time.sleep(5)
baixar = driver.find_element_by_xpath('/html/body/div[13]/drop-down-list/ng-transclude/ng-repeat[4]/drop-down-list-item/ng-transclude/ng-switch/div')
baixar.click()